#
# Easyname REST API client configuration.
#

url: "https://api.easyname.com"
user-id: 0
user-email: "bob@example.com"
api-key: "aaaaaaaa"
api-authentication-salt: "aaaaaaaa%sbbbbbbbb%scccccccc"
api-signing-salt: "AaaBbbCccDddEeeFffGggHhh"
